# Use the same image as our Dockerfile
image: python:slim

# These two settings let us cache pip-installed packages,
# it came from the default template
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  # Make Mozilla Firefox run headless
  MOZ_HEADLESS: "1"
cache:
  paths:
    - .cache/pip

# "setUp" phase, before the main build
before_script:
  - python --version; pip --version
  - pip install virtualenv
  - virtualenv .venv
  - source .venv/bin/activate

test:
  script:
    - pip install -r requirements.txt
    # unit tests
    - python src/manage.py test lists accounts
    # (if those pass) ll tests incl. functional.
    - apt update -y && apt install -y firefox-esr
    - pip install selenium
    - cd src && python manage.py test